### PR TITLE
[REWRITE] Rewrite RendangBOT

### PR DESCRIPTION
**Pull request by Hazmi35**
Ok, i think this repository is such a mess, should we rewrite this?

### CODE REVIEW

**Comment by vzrenggamani** [comment]
*Need to figure what will be doing for this?*

Correct me, should we use Issues instead of PR ?

**Comment by Hazmi35** [comment]
> _Need to figure what will be doing for this?_
> 
> Correct me, should we use Issues instead of PR ?

Cleaning Rendang's code, maybe, but not for this one

**Comment by KurokuTetsuya** [comment]
P, gajawab PKI

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
p

**Comment by KurokuTetsuya** [comment]
p

**Comment by KurokuTetsuya** [comment]
p

**Comment by KurokuTetsuya** [comment]
pP

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by SharifPoetra** [comment]
dihh gw di remove dong padahal sejak awal rencana rendang ide gw:(

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
P

**Comment by KurokuTetsuya** [comment]
PP

**Comment by KurokuTetsuya** [comment]
PP

**Comment by KurokuTetsuya** [comment]
https://github.com/discordbotsNation/Rendang/pull/13#issuecomment-511830827 kwaawkookwa iya rafi kan egois, goblok

**Comment by KurokuTetsuya** [comment]
tolol dia
awkowaokkowa

**Comment by KurokuTetsuya** [comment]
MALAH DIMERGE WKAOKOWAKOWAOKWA

**Pull request merged**
